####
GET http://localhost:5000/locations HTTP/1.1

####
GET http://localhost:5000/near HTTP/1.1
####
POST http://localhost:5000/locations HTTP/1.1
content-type: application/json

{
    "name": "Ulaanbaatar, Mongolia",
    "category":"Country",
    "location": [106.7617863,47.8917951]    
}
####
POST http://localhost:5000/locations HTTP/1.1
content-type: application/json

###
POST http://localhost:5000/locations HTTP/1.1
content-type: application/json

[
  {    
    "name": "WaleMart",
    "category": "Market",
    "location": [-91.993186,41.008382]
  },
  {
    "name": "MUM",
    "category": "University",
    "location": [-91.967291,41.018059]
  },
  {
    "name": "Des Monnes",
    "category": "City",
    "location": [-93.6765561,41.5667771]
  },    
  {
    "name":"Hyvee",
    "category":"Rest",
    "location":[
        -91.9684817,
        41.011239        
        ]
 }
]



####
GET http://localhost:3000/query1 HTTP/1.1

####
GET http://localhost:3000/query2 HTTP/1.1

####
GET http://localhost:3000/query3 HTTP/1.1

####
GET http://localhost:3000/query4 HTTP/1.1
####
GET http://localhost:3000/query5 HTTP/1.1
####
GET http://localhost:3000/query6 HTTP/1.1
####
GET http://localhost:3000/query7 HTTP/1.1
####
GET http://localhost:3000/query8 HTTP/1.1
####
GET http://localhost:3000/query9 HTTP/1.1
####
GET http://localhost:3000/query10 HTTP/1.1
####
GET http://localhost:3000/query11 HTTP/1.1
####
GET http://localhost:3000/query12 HTTP/1.1
####
GET http://localhost:3000/query13 HTTP/1.1
####
GET http://localhost:3000/query14 HTTP/1.1
####
GET http://localhost:3000/query15 HTTP/1.1
####
GET http://localhost:3000/query16 HTTP/1.1
####
GET http://localhost:3000/query17 HTTP/1.1
####
GET http://localhost:3000/query18 HTTP/1.1
####
GET http://localhost:3000/query19 HTTP/1.1
####
GET http://localhost:3000/query20 HTTP/1.1
####
GET http://localhost:3000/query21 HTTP/1.1
####
GET http://localhost:3000/query22 HTTP/1.1
####
GET http://localhost:3000/query23 HTTP/1.1

