GET http://localhost:4000/secret HTTP/1.1

####
GET http://localhost:5000/lectures HTTP/1.1

####
GET http://localhost:5000/lectures/CS572 HTTP/1.1

####
POST http://localhost:5000/lectures HTTP/1.1
content-type: application/json

{
    "course": "WAP",
    "lecture": "03"
}

####
DELETE http://localhost:5000/lectures/WAP HTTP/1.1

####
PUT  http://localhost:5000/lectures/WAP HTTP/1.1
content-type: application/json

{
    "course": "WAP",
    "lecture": "01"
}

####
GET http://localhost:5000/search/03 HTTP/1.1
